spring.datasource:
  url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: false
camunda.bpm:
  client:
    base-url: http://localhost:8080/engine-rest
    max-tasks: 1
    use-priority: true
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  job-execution:
      deployment-aware: true
server.port: 8081
